# Use Python 3.9 slim version
FROM python:3.9-slim

# Set environment variables
ENV PYTHONPATH=/app/src

# Set the working directory first
WORKDIR /app

# Install required dependencies
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy the rest of the application code
COPY . /app/