x-worker-template: &worker-template
  build:
    context: .
    dockerfile: Dockerfile.service
  command: ["celery", "-A", "microservices.celery_app", "worker", "--loglevel=info"]
  volumes:
    - ./src:/app/src
  environment:
    - PYTHONPATH=/app/src
  depends_on:
    - redis

services:
  redis:
    image: redis:alpine

  fbref_worker:
    <<: *worker-template
    image: celery-base:fbref

  sofascore_worker:
    <<: *worker-template
    image: celery-base:sofascore

  transfermarkt_worker:
    <<: *worker-template
    image: celery-base:transfermarkt

  whoscored_worker:
    <<: *worker-template
    image: celery-base:whoscored

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.service
    command: ["celery", "-A", "microservices.celery_app", "beat", "--loglevel=info"]
    volumes:
      - ./src:/app/src
    depends_on:
      - redis